### ISSUE TITLE
Doesn't seem to work via Tampermonkey on Linux Firefox/Chrome

### ISSUE THREAD

**Issue by HazySkies** [firlin123/firlin123.github.io#2]
No dialogue box or similar appears at all even with the script seemingly running.

According to the script editor, there seems to be syntax errors on lines 28, 46 and 53: 
```
eslint: no-implicit-globals - Global variable leak, declare the variable if it is intended to be local.
eslint: no-undef - 'description' is not defined.
```
![ai-meme-script-errors](https://user-images.githubusercontent.com/127673667/232418439-7867aae6-5c22-4efd-867b-b074e3da2e47.png)

This was tested on a Linux Mint 21 system with Firefox v111.0 and Chrome 109.0.5414.119

**Comment by firlin123** [comment]
The site's gpt backend is dead and I've lost Interest. Won't be updating this.
